server:
  servlet:
    context-path: /api
  port: 8090
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/question_bank?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true
    username: root
    password: RJCwXr7M
mybatis:
  mapper-locations: classpath:mapper/*.xml
